# Generated by Django 5.0.6 on 2024-05-23 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='approvals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15)),
                ('lastname', models.CharField(max_length=15)),
                ('dependants', models.IntegerField()),
                ('applicantincome', models.FloatField()),
                ('coapplicantincome', models.FloatField()),
                ('loanamount', models.FloatField()),
                ('loanterm', models.IntegerField()),
                ('credithistory', models.FloatField(default=0)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('married', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('graduatededucation', models.CharField(choices=[('Graduate', 'Graduate'), ('Not_Graduate', 'Not_Graduate')], max_length=15)),
                ('selfemployed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('area', models.CharField(choices=[('Urban', 'Urban'), ('Rural', 'Rural'), ('Semiurban', 'Semiurban')], max_length=10)),
            ],
        ),
    ]
