# Generated by Django 5.0.6 on 2024-05-23 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='approvals',
            new_name='approval',
        ),
    ]
