# Generated by Django 5.1a1 on 2024-06-02 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theAPI', '0002_rename_approvals_approval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approval',
            old_name='applicantincome',
            new_name='ApplicantIncome',
        ),
        migrations.RenameField(
            model_name='approval',
            old_name='coapplicantincome',
            new_name='CoapplicantIncome',
        ),
        migrations.RenameField(
            model_name='approval',
            old_name='credithistory',
            new_name='Credit_History',
        ),
        migrations.RenameField(
            model_name='approval',
            old_name='dependants',
            new_name='Dependants',
        ),
        migrations.RenameField(
            model_name='approval',
            old_name='graduatededucation',
            new_name='Education',
        ),
        migrations.RenameField(
            model_name='approval',
            old_name='firstname',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='approval',
            old_name='gender',
            new_name='Gender',
        ),
        migrations.RenameField(
            model_name='approval',
            old_name='lastname',
            new_name='Last_Name',
        ),
        migrations.RenameField(
            model_name='approval',
            old_name='loanamount',
            new_name='LoanAmount',
        ),
        migrations.RenameField(
            model_name='approval',
            old_name='loanterm',
            new_name='Loan_Amount_Term',
        ),
        migrations.RenameField(
            model_name='approval',
            old_name='married',
            new_name='Married',
        ),
        migrations.RenameField(
            model_name='approval',
            old_name='area',
            new_name='Property_Area',
        ),
        migrations.RenameField(
            model_name='approval',
            old_name='selfemployed',
            new_name='Self_Employed',
        ),
    ]
